### ISSUE TITLE
wet-boew-php 4.0

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew-php#168]
Hi @upsonp,

Is there a working version of wet-boew / wet-boew-php for WET 4.0 available anywhere? I downloaded both and, while wet-boew works, I can't seem to get it to work with wet-boew-php using the included demo-php site even after configuring the config/config.php file with my paths.

Best regards,

Michael

**Comment by upsonp** [comment]
Hi @michael-milette 

Yes, there is a 4.0 Branch https://github.com/wet-boew/wet-boew-php/tree/v4.0

I'm actually using it with the BIO website I manage, we never got around to making it the master branch in the project.

**Comment by michael-milette** [comment]
Hi @upsonp ,

Even with the right branch, it still doesn't seem to have correct paths. I read in one of the source code files that it works for you when the WET folders are placed in the webroot.

Having the files in the webroot doesn't work for us because we have multiple sites on the same webserver and this location would conflict between sites, especially if they were using different themes.

Would it be ok with you if I modified the code so that these files and folders could be placed anywhere? Naturally I would appreciate it if these changes could then be integrated into the core code so that they automatically get maintained in the future.

Let me know if you have any questions.

Best regards,

Michael

**Comment by upsonp** [comment]
Hi @michael-milette,

I think I understand the issue. There are hooks built in so the WET folders don't have to go in the site root. I had a similar situation to you on the new IM&TS provided web server the BIO site is on.

I thought I had documented it, but I guess not, or at least it never made it to the wiki.

So with how my site is set up I have a "config-path.php" file that gets called at the top of all my pages. The config-path.php file sets the path to the BIO site along with the location of the WET 4.0 and WET PHP 4.0 variants.

I don't have a simple version of how this works at the moment because the paths depend on what server it's being served from, but here's my best effort to simplify it. I'll provide it here and hopefully any questions you have can help me document it.

```php
<?php
	$_SITE["wb_theme"] = "theme-gcwu-fegc";

	//location of the website "web" root for this site
	$_SITE['ROOT'] = "REPLACE_WITH_HTML_ROOT";
		
	//use the server root as the "site" root unless a different root is required
	$_SITE['SITE_ROOT'] = $_SERVER['DOCUMENT_ROOT'];
		
	//create an absolute path from "site" root and "web" root
	$_SITE['DOCUMENT_ROOT'] = $_SITE['SITE_ROOT'] . "REPLACE_WITH_INCLUDE_ROOT";
		
	//override the $_SERVER['DOCUMENT_ROOT'] root, and use $_SITE['DOCUMENT_ROOT'] instead 
	$_SERVER['DOCUMENT_ROOT'] = "";
		
	//location of the WET 4.0 /dist folder
	$_SITE['wb_core_root'] = "/share/wet/4.0.6/" . $_SITE["wb_theme"];
	
	//location of the PHP variant /dist-php folder
	$_SITE['wb_php_root'] = "/u01/var/www/libs/wetphpvariant/4.0";
?>
```

**Comment by michael-milette** [comment]
Hi @upsonp ,

I did see references to that in the source code documentation, specifically the config.php files.

	/* **************************************
	 * The config-path.php file is intended to be used with the demos-php to
	 * simplify deployment to various webservers. Change the $_SITE['wb_php_root']
	 * and $_SITE['wb_core_root'] variables to point to the directory where
	 * the /dist-php and core /dist folders respectivly exist
	 * 
	 * DEV NOTE:
	 * my personal setup has the WET core themes at the root of the server so:
	 * /demos-php
	 * /dist-php
	 * /theme-base
	 * /theme-gcwu-fegc
	 * etc...
	 * 
	 * I've give the PHP distribution themes the same names as the core theme folders
	 */

However, I can't see where where to put this config-path.php file in order to get the demo site working. I searched all of the source code for the string "config-path.php" and could not find it.

**Comment by michael-milette** [comment]
Here is some documentation I've prepared for getting the demo site working:

*Getting started with the WET-BOEW-PHP demo site*

This documentation assumes that you already have a working webserver that meets the minumum requirements.

From your webroot directory (root of your website's directory, sometimes also called www or htdocs), do the following commands:

    mkdir wetsite
    cd wetsite
    git clone https://github.com/wet-boew/wet-boew-dist.git
    git clone https://github.com/wet-boew/wet-boew-php/
    cd wet-boew-php
    git checkout v4.0

What you end up with is:

    wet-boew-php/
        demos-php/
        dist-php/
    wet-boew-dist/
        lots of files and folders
        
You can optionally download additional wet themes by doing:

    cd ..
    git clone https://github.com/wet-boew/themes-dist.git wet-boew-themes

This creates wet-boew-themes which contains lots of files and folders whose structure looks a lot like that found in wet-boew-dist.

    cd wet-boew-themes
    git checkout name_of_theme
    
...where *name_of_theme* can be one of the following:

* GCWeb
* theme-gcwu-fegc
* theme-ogpl
* theme-base
* theme-gc-intranet

*[missing configuration steps here]*

Go to the following address using your web browser, replacing localhost with your domain name.

http://localhost/wetsite/wet-boew-php/demos-php/

Getting the demo site working should be just about as simple as that. In fact, it should be possible to have someone follow these instructions without any configuration fiddling and end up with a working site, even if it may not be with with the theme they want.

What do you think?

Best regards,

Michael

**Comment by michael-milette** [comment]
Just noticed is that, out of the box, wet-boew-php includes files to support the *theme-base* and *theme-gcwu-fegc* themes however the wet-boew-dist only includes the *theme-wet-boew* theme.

**Comment by upsonp** [comment]
Thanks @michael-milette your documentation is great.

The missing configuration step might be a bit harder to hash out.

This is what one of my webpages looks like, I call it the boiler plate because it's the same for every page with the exception of the first few lines that set page specific variables. You can see on the sixth line I include the path-config.php, which is where all the other configuration for the site takes place. From then on I try to use <code>$_SITE</code> instead of <code>$_SERVER</code> to be sure I'm using the proper paths. Unfortunately this all depends on the path-config.php file being in some known location before you start.

```php
<?php 
	$_PAGE['lang1'] = "en";
	$_PAGE['title_en'] = "Help";
	$_PAGE['issued'] = "2011-08-02"; 

	include_once $_SERVER["DOCUMENT_ROOT"]."/sites/bio/templates/path-config.php";
	include_once $_SITE['DOCUMENT_ROOT'] . "/templates/2-col-php-header-1.php";
?>
<!--custom metadata-->
<!--end of custom metadata-->

<?php include_once $_SITE['DOCUMENT_ROOT'] . "/templates/2-col-php-header-2.php"; ?>

<!--custom css-->
<!--end of custom css-->

<?php include_once $_SITE['DOCUMENT_ROOT'] . "/templates/2-col-php-header-3.php"; ?>
```
I'm sorry about the other themes, when I developed the theme-wet-boew theme WET 4.0 was still in development and I was doing my best to upgrade and migrate my site using the PHP variant. There were what seemed like weekly changes to how the core WET 4.0 worked so I didn't bother doing the other themes because they seemed likely to change. Then I just never got around to going back to implementing the other themes. I still plan on doing it, I just can't commit to when.

**Comment by michael-milette** [comment]
@upsonp , does the wet-boew-php/demo-php site actually work?

**Comment by upsonp** [comment]
Not for wet 4.0, I think it's still on wet 3, we should get that changed over not that it seems the core WET 4 is stable.

**Comment by michael-milette** [comment]
That would explain a few things. I'll work on it a bit more today and share my work with you. It won't be a finished product but I should have a few pages working.

**Comment by michael-milette** [comment]
The demos-php site included with WET-BOEW-PHP now works.
