### ISSUE TITLE
Base theme footer background is the wrong colour

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew-php#172]
The background colour of Footer in the Base theme, of the demos-php site, should be grey, not red.

WHAT IT IS

![image](https://cloud.githubusercontent.com/assets/3808579/11640785/76e6422a-9d02-11e5-9f69-2d41a5292f0f.png)

WHAT WAS EXPECTED (as per WET-BOEW HTML dist)

![image](https://cloud.githubusercontent.com/assets/3808579/11640900/34422410-9d03-11e5-8d4d-0b31c7c96413.png)

**Comment by upsonp** [comment]
I'll have to get setup to do some development on this part. There's obviously a div tag missing somewhere.

**Comment by upsonp** [comment]
I have to say, I REALLY like what you've done with the config files. I pick up something new every time you get involved ^_^

**Comment by michael-milette** [comment]
Thanks Patrick! 

I wasn't sure how you would feel about the use of a cookie. I use this technique in Moodle to demonstrate how the same site could look using different themes to clients except that I put the options to switch in the WET menu. Because you use ajax to retrieve the menu, I am not sure there is a way to modify it to add theme switching links without adding some Javascript. Anyway, while great for demonstration, we disable this in production environments of course. It wouldn't be good if the public started switching themes on their own. I actually got the idea from a demo of WET for Drupal at a WET CodeFest here in Ottawa a few years back. The cool thing about using the cookie is that it only affects your session.

As for the location of the config file, I really wanted to find a way to put it somewhere so that it would not get clobbered each time I updated the theme. I also like just having one config file. The thought of having to configure a separate config file for each theme each time I updated WET-BOEW-PHP wasn't working for me. It's always a challenge to place that config file.

Hope getting rid of the individual content files for each theme won't cause any problems. In my humble opinion, data should be separate from presentation but I know that there will likely be issues that will come up as a result of different names for classes and id's. Hopefully we can work around that instead of having to manage multiple sets of content files.

Anyway, glad you like the changes. As I begin to integrate WET-BOEW-PHP into Moodle, I may come back to you with some additional changes.

Thank you for all your efforts @upsonp. I really appreciate everything you do for the project.

Best regards,

Michael Milette

**Comment by upsonp** [comment]
I have a few updates I just merged in to fix the footer layout. I was right it was just a missing div, but there were a few other css classes that needed to be stuck in too.

> Hope getting rid of the individual content files for each theme won't cause any problems.

I'll figure it out. The important thing is to be consistent. With you're setup all I had to do was copy the <code>/config/wetconfig.php</code> to the server root. Although that was the issue I ran into with the new IM&TS server. They wanted my site completely self contained I wasn't allowed to put things in the server root, which was a major pain in the arse given the odd path to the location on the server to the site that changes depending on if it's my local machine, the dev server, the test server, the public server.

We eventually came up with a magic spell where when I commit updates to the SVN the site is auto-deployed to the webserver and certain key word phrases are replaced with the server paths for that server. This isn't too much of a departure from what I already had except I have config-path.php instead of wetconfig.php.

> Hope getting rid of the individual content files for each theme won't cause any problems.

I'm pretty sure all the content files were the same anyway. I am having a bit of trouble getting the cookie working to swap themes. Using <code>?theme=theme-gcwu-fegc</code> returns "The theme-gcwu-fegc theme is not installed on this site.", I'm pretty sure it's because I don't have the theme in the place config.php is looking for it. I'll keep playing with it.

**Comment by upsonp** [comment]
Scratch that last part using <code>?theme=gcwu-fegc</code> worked. I just had to drop the word 'theme'

**Comment by michael-milette** [comment]
I just fetched the latest changes and can confirm that the background colour in the footer now appear correct.

As for the content, most of it was identical. There were however a few differences (extra divs) in a few files some themes which I hope won't be a problem. I didn't really spend a lot of time comparing them. I just looked at which set of theme files seemed most complete and up to date and discarded the rest. I ended up going with the gcwu-fegc theme. One of the beneficial side effects is that the language switcher for the base and wet-boew themes automagically started working so I didn't have to go and fix that issue :-) 

Anyway, I am closing this issue as it seems to have been resolved.

Best regards,

Michael
